#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pth
Version  : 2.0.7
Release  : 3
URL      : http://ftp.gnu.org/gnu/pth/pth-2.0.7.tar.gz
Source0  : http://ftp.gnu.org/gnu/pth/pth-2.0.7.tar.gz
Summary  : GNU Pth - The GNU Portable Threads
Group    : Development/Tools
License  : LGPL-2.1
Requires: pth-bin
Requires: pth-lib
Requires: pth-doc
BuildRequires : libtool-dev
BuildRequires : m4
Patch1: build.patch

%description
Pth is a very portable POSIX/ANSI-C based library for Unix platforms which
provides non-preemptive priority-based scheduling for multiple threads of
execution (aka ``multithreading'') inside event-driven applications. All
threads run in the same address space of the server application, but each
thread has it's own individual program-counter, run-time stack, signal
mask and errno variable.

The thread scheduling itself is done in a cooperative way, i.e., the
threads are managed by a priority- and event-based non-preemptive
scheduler. The intention is that this way one can achieve better
portability and run-time performance than with preemptive scheduling. The
event facility allows threads to wait until various types of events occur,
including pending I/O on filedescriptors, asynchronous signals, elapsed
timers, pending I/O on message ports, thread and process termination, and
even customized callback functions.

Additionally Pth provides an optional emulation API for POSIX.1c threads
("Pthreads") which can be used for backward compatibility to existing
multithreaded applications.

%package bin
Summary: bin components for the pth package.
Group: Binaries

%description bin
bin components for the pth package.


%package dev
Summary: dev components for the pth package.
Group: Development
Requires: pth-lib
Requires: pth-bin

%description dev
dev components for the pth package.


%package doc
Summary: doc components for the pth package.
Group: Documentation

%description doc
doc components for the pth package.


%package lib
Summary: lib components for the pth package.
Group: Libraries

%description lib
lib components for the pth package.


%prep
%setup -q -n pth-2.0.7
%patch1 -p1

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pth-config

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/share/aclocal/*.m4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
